baseURL = 'https://jongyongpark.github.io/'
title = "RyanLabs"
theme = 'PaperMod'
# paginate = 10
languageCode = "ko"
defaultContentLanguage = "ko"
# paginate = 10

ignoreFiles = ["/private/"]


[params]
  homeInfoParams = false

  [params.profileMode]
    enabled = true
    title = "Ryan"
    subtitle = "ğŸ’» DevSecOps Engineer"
    imageUrl = "images/profile.png"
    imageTitle = "RyanLabs"

  [[params.profileMode.buttons]]
    name = "Email"
    url = "mailto:lovemoneyjoy@gmail.com"

  [[params.profileMode.buttons]]
    name = "Website"
    url = "https://your-site.com"

  [[params.profileMode.buttons]]
    name = "YouTube"
    url = "https://youtube.com/yourchannel"

  [[params.profileMode.buttons]]
    name = "GitHub"
    url = "https://github.com/JongYongPark"

  [[params.profileMode.buttons]]
    name = "Instagram"
    url = "https://instagram.com/yourhandle"

# [params]
#   description = "DevSecOps ê°œë°œì ë…¸íŠ¸"
#   author = "Ryan"
#   defaultTheme = "auto"
#   homeInfoParams = false # ìµœê·¼ í¬ìŠ¤íŠ¸ë§Œ ë³´ì´ë„ë¡ true â†’ false ì„¤ì •
#   [params.profileMode]
#     enabled = true
#     title = "Ryan"
#     subtitle = "Creator & Data Lover"
#     imageUrl = "/images/profile.jpg"
#     imageWidth = 150
#     imageHeight = 150

# [params.social]
#   github = "https://github.com/JongYongPark"
#   email = "lovemoneyjoy@gmail.com"
#   youtube = ""
#   instagram = ""

[menu]
  [[menu.main]]
    name = "ê²€ìƒ‰"
    url = "/search/"
    weight = 1

  [[menu.main]]
    name = "ì¹´í…Œê³ ë¦¬"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "íƒœê·¸"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "ì—°ë„"
    url = "/archives/"
    weight = 4

  [[menu.main]]
    name = "ê°•ì˜"
    url = "/lectures/"
    weight = 5

  [[menu.main]]
    name = "ì–´ë°”ì›ƒë¯¸"
    url = "/about/"
    weight = 6


[outputs]
  home = ["HTML", "RSS", "JSON"]   # ë°˜ë“œì‹œ ìˆì–´ì•¼ í•¨

[params.search]
  enabled = true

[params.assets]
  customCSS = ["css/custom.css"]

[taxonomies]
  category = "categories"
  tag = "tags"

