baseURL = 'https://jongyongpark.github.io/'
languageCode = 'ko-kr'
title = "RyanPark's DevSecOps"
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  mainSections = ["posts"]
  
[params.profileMode]
  enabled = false
  
[params.homeInfoParams]
  Title = "RyanPark's DevSecOps Blog ğŸ‘‹"
  Content = """
Security & DevOps Engineering Blog

ìµœì‹  ë³´ì•ˆ ë° DevOps ê´€ë ¨ ê¸°ìˆ  ì •ë³´ë¥¼ ê³µìœ í•©ë‹ˆë‹¤.
"""

[params.assets]
  favicon = "favicon.ico"
  favicon16x16 = "favicon-16x16.png"
  favicon32x32 = "favicon-32x32.png"
  apple_touch_icon = "apple-touch-icon.png"
  
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# [permalinks]
#   post = "/post/:categories/:slug/"

[menu]
  [[menu.main]]
    identifier = "search"
    name = "ê²€ìƒ‰"
    url = "/search/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "ì¹´í…Œê³ ë¦¬"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "íƒœê·¸"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "archives"
    name = "ì—°ë„"
    url = "/archives/"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "ì–´ë°”ì›ƒë¯¸"
    url = "/about/"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]